language: node_js
sudo: false
node_js:
  - "node"
install:
  - yarn global add codecov
  - yarn global add istanbul
  - yarn
script:
  - istanbul cover ./node_modules/lab/bin/lab --report lcovonly  -- -l && codecov
branches:
  only:
    - master