language: node_js
sudo: false
node_js:
  - "node"
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install
script:
  - istanbul cover ./node_modules/lab/bin/lab --report lcovonly  -- -l && codecov
branches:
  only:
    - master
